In [1]:
from IPython.display import display, HTML

import pandas as pd

In [2]:
columns = ['ReceiptId', 'ItemName', 'Lv1Catagory', 'Lv2Catagory',
           'Lv3Catagory', 'Lv4Catagory', 'Lv5Catagory', 'Lv6Catagory',
           'Brand', 'VendorName', 'Price', 'Qty', 'Time', 'Date',
           'StoreName', 'StoreCategory', 'CompanyName', 'AccountNum']
df = pd.read_csv('transaction_fact.csv', names=columns, header=None)
display(df.head())
display(df.info())

/Users/far/.pyenv/versions/miniconda3-4.3.30/envs/senior-proj-ai/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (17) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ReceiptId,ItemName,Lv1Catagory,Lv2Catagory,Lv3Catagory,Lv4Catagory,Lv5Catagory,Lv6Catagory,Brand,VendorName,Price,Qty,Time,Date,StoreName,StoreCategory,CompanyName,AccountNum
0,2022102-1087458,F9E300th1.8M 3-WaySurgeProtector1.8m:490,ALL,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,42100 - COMPUTER ACCESSORIES,42160 - OTHER COMPUTER ACCESSORIES,42161 - OTHER COMPUTER ACCESSORIES,NaN,Forklifts Comcare Co.,14700.0,1.0,16:03:18.0000000,2017-12-13,PM The Park,PM,"PINK POMELO,Ltd.",20274
1,2020101-1105832,F9E300th1.8M 3-WaySurgeProtector1.8m:490,ALL,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,42100 - COMPUTER ACCESSORIES,42160 - OTHER COMPUTER ACCESSORIES,42161 - OTHER COMPUTER ACCESSORIES,NaN,Forklifts Comcare Co.,14700.0,1.0,10:54:36.0000000,2017-12-21,PM 4PM,PM,"PINK POMELO,Ltd.",9200011761
2,2020101-1021987,F9E300th1.8M 3-WaySurgeProtector1.8m:490,ALL,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,42100 - COMPUTER ACCESSORIES,42160 - OTHER COMPUTER ACCESSORIES,42161 - OTHER COMPUTER ACCESSORIES,NaN,Forklifts Comcare Co.,14700.0,1.0,11:48:54.0000000,2016-08-13,PM 4PM,PM,"PINK POMELO,Ltd.",9200019826
3,2020101-1080992,F9E300th1.8M 3-WaySurgeProtector1.8m:490,ALL,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,42100 - COMPUTER ACCESSORIES,42160 - OTHER COMPUTER ACCESSORIES,42161 - OTHER COMPUTER ACCESSORIES,NaN,Forklifts Comcare Co.,14700.0,1.0,13:11:04.0000000,2017-07-13,PM 4PM,PM,"PINK POMELO,Ltd.",1101501189
4,2020103-1040876,F9E300th1.8M 3-WaySurgeProtector1.8m:490,ALL,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,42100 - COMPUTER ACCESSORIES,42160 - OTHER COMPUTER ACCESSORIES,42161 - OTHER COMPUTER ACCESSORIES,NaN,Forklifts Comcare Co.,14700.0,1.0,20:46:50.0000000,2017-01-13,PM 4PM,PM,"PINK POMELO,Ltd.",2795

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1192241 entries, 0 to 1192240
Data columns (total 18 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReceiptId      1192241 non-null  object
 1   ItemName       1192241 non-null  object
 2   Lv1Catagory    1192241 non-null  object
 3   Lv2Catagory    1192241 non-null  object
 4   Lv3Catagory    1188355 non-null  object
 5   Lv4Catagory    1143979 non-null  object
 6   Lv5Catagory    1097977 non-null  object
 7   Lv6Catagory    1080003 non-null  object
 8   Brand          281670 non-null   object
 9   VendorName     1160848 non-null  object
 10  Price          1192241 non-null  float64
 11  Qty            1192241 non-null  float64
 12  Time           1192241 non-null  object
 13  Date           1192241 non-null  object
 14  StoreName      1192241 non-null  object
 15  StoreCategory  1192241 non-null  object
 16  CompanyName    1192241 non-null  object
 17  AccountNum     1192241 non-null  object
dtypes: float64(2), object(16)
memory usage: 163.7+ MB

None

In [3]:
df = df[['ReceiptId', 'Lv2Catagory', 'Lv3Catagory', 'Qty', 'StoreName', 'Date', 'AccountNum']]
df = df[df['StoreName'] == 'PM 4PM']
display(df)

,ReceiptId,Lv2Catagory,Lv3Catagory,Qty,StoreName,Date,AccountNum
1,2020101-1105832,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,1.0,PM 4PM,2017-12-21,9200011761
2,2020101-1021987,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,1.0,PM 4PM,2016-08-13,9200019826
3,2020101-1080992,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,1.0,PM 4PM,2017-07-13,1101501189
4,2020103-1040876,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,1.0,PM 4PM,2017-01-13,2795
5,2020101-1071109,40000 - LIFESTYLES,42000 - IT & GADGET ACCESSORIES,1.0,PM 4PM,2017-05-19,137994
...,...,...,...,...,...,...,...
1192224,2020104-1076796,40000 - LIFESTYLES,41000 - STATIONERY,1.0,PM 4PM,2018-08-23,9200070898
1192226,2020103-1136692,40000 - LIFESTYLES,41000 - STATIONERY,1.0,PM 4PM,2018-08-11,9200085629
1192227,2020104-1071877,40000 - LIFESTYLES,41000 - STATIONERY,1.0,PM 4PM,2018-08-03,9200321206
1192231,2020103-1126480,40000 - LIFESTYLES,41000 - STATIONERY,1.0,PM 4PM,2018-06-13,9200290880
1192234,2020101-1133044,40000 - LIFESTYLES,41000 - STATIONERY,2.0,PM 4PM,2018-05-12,125486

In [4]:
df.to_csv('transaction.csv', index=False)